    name: Bitepixel Build

on:
  push:
    branches:
      - '**'

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        type: [debug, release]
        include:
          - type: debug
            afat: assembleAfatDebug
          - type: release
            afat: assembleAfatRelease
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Free up disk space
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false
          android: false

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - uses: nttld/setup-ndk@v1.4.2
        id: setup-ndk-r21e
        with:
          ndk-version: r21e
          link-to-sdk: true

      - name: Install additional NDK for JNI build
        run: yes | "$ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager" "ndk;27.2.12479018"

      - name: Configure build vars
        run: |
          vars=gradle.properties
          echo "org.gradle.workers.max=1" >> $vars
          echo "APP_ID=${{ secrets.APP_ID }}" >> $vars
          echo "APP_HASH=${{ secrets.APP_HASH }}" >> $vars
          echo "RELEASE_KEY_PASSWORD=${{ secrets.ALIAS_PASS }}" >> $vars
          echo "RELEASE_KEY_ALIAS=${{ secrets.ALIAS_NAME }}" >> $vars
          echo "RELEASE_STORE_PASSWORD=${{ secrets.KEYSTORE_PASS }}" >> $vars
          echo "RELEASE_KEYSTORE_FILE=$PWD/TMessagesProj/config/release.keystore" >> $vars
          echo "ADDITIONAL_BUILD_NUMBER=0" >> $vars
          echo "USER_REPO=$GITHUB_REPOSITORY" >> $vars
          echo "CHECK_UPDATES=0" >> $vars
          echo "NATIVE_DEPS_NDK_DIR=${{ steps.setup-ndk-r21e.outputs.ndk-path }}" >> $vars

      - name: Build
        run: |
          sudo apt update
          sudo apt -y install ninja-build meson unzip gperf
          ./gradlew :TMessagesProj_App:${{ matrix.afat }}

      - name: Collect APK
        run: |
          mkdir -p artifact
          mv TMessagesProj_App/build/outputs/apk/afat/${{ matrix.type }}/app.apk \
             "artifact/Bitepixel-${{ matrix.type }}.apk"

      - uses: actions/upload-artifact@v4
        with:
          name: bitepixel-${{ matrix.type }}
          path: artifact/
